config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  # devise_scope :user do #ログイン関係のパス名をloginとlogoutに変更
  #   get "sign_up", to: "users/registrations#new"
  #   post "", to: "users/registrations#create"
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'views#index'

  resources :views, only: [:index] do
    collection do
      get 'news'
      get 'about'
    end
  end

  resources :products, only: [:index, :show, :destroy] do
    collection do
      get 'cart'
      patch 'purchase'
      post 'pay'
      get 'history'
      post 'create', to: "products#create", as: :create_order
    end
    resources :pays, only: [:index] do
      collection do
        post 'pay'
        get 'done'
      end
    end
  end
  resources :users, only: [:index] do
    collection do
      get 'address'
      post 'address_create'
      get 'card'
      post 'card_create'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :sizes
  has_many :colors
  has_many :orders
  belongs_to :category
  belongs_to :status
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!, only: [:create, :cart, :history, :destory]
  def index
    @products = Product.order("id ASC").limit(12)
  end

  def show
    @product = Product.find(params[:id])
    @images = @product.images
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
    else
      redirect_to product_path(@order.product_id)
    end
  end

  def cart
    @orders = Order.where(user_id: current_user.id, order_status_id: 1)
    @address = Address.where(user_id: current_user.id)
  end

  def purchase
    @orders = Order.where(user_id: current_user.id, order_status_id: 1)
    if @orders.update(order_status_id: 2) 
      redirect_to cart_products_path
    else       
      redirect_to cart_products_path
    end
  end

  def pay
    card = Card.where(user_id: current_user.id).first
    @orders = Order.where(user_id: current_user.id, order_status_id: 1)
    @total_price = (@orders.product.price.sum * 1.1)
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    charge = Payjp::Charge.create(
    amount: @total_price,
    customer: card.customer_id,
    currency: :'jpy',
    )
    @orders.update(order_status_id: 2)
    if @orders.save(validate: false)
      redirect_to cart_products_path
    else
      flash[:notice] = '問題が発生して処理を中止しました。'
      redirect_to root_path
    end
  end

  def history
    @orders = Order.where(user_id: current_user.id, order_status_id: 2)
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to cart_products_path
    else
      redirect_to cart_products_path
    end
  end

  private

  def order_params
    params.require(:order).permit(:count, :size, :color, :product_id).merge(user_id: current_user.id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/cart.html.haml
= render partial: 'layouts/header-black'

.cart
  .cart-space
    - @total_price = 0
    - @orders.each do |order|
      .cart-count
        = " PRODUCT: #{order.product.name} ,　"
        = " PRICE: ¥#{order.product.price.to_s(:delimited)} ,　"
        = " COUNT: #{order.count} ,　"
        = " SIZE: #{order.size} ,　"
        = " COLOR: #{order.color} 　"
        = " →　TOTAL-PRICE: ¥#{(order.product.price * order.count).to_s(:delimited)} "
        - @total_price += (order.product.price * order.count)
      .cancel-btn-space
        = button_to "CANCEL", "#{order.id}", method: :delete , class: "cancel-btn" 
  .please-scroll
    - if @orders.length > 2
      %p
      ↑　please scroll　↑
      %p
      check products!!
  .total-space
    .price
      = " PRICE: 　¥#{@total_price.to_s(:delimited)} "
    .plus-space
      = "+"
    .tax-price
      = " TAX: 　¥#{(@total_price * 0.1).floor.to_s(:delimited)}"
    .equal-space
      = "="
    .total-price
      = " TOTAL-PRICE: 　¥#{(@total_price + (@total_price * 0.1)).floor.to_s(:delimited)} "
  - if @address.length === 0
    = link_to 'Address Register', address_users_path, class: 'purchase_btn'
  - else
    - if @orders.length > 0
      = link_to 'Purchase', purchase_products_path(@orders), method: :patch, class: 'purchase_btn'
  -# %form{action: "/products/pay", :method => "post"}
  -#   %script.payjp-button{"data-key" => "pk_test_027fe68f7b662bdff3d0cf1c", :src => "https://checkout.pay.jp/"}

app/views/products/create.html.haml
.product-create
  %p.order-clear Added to cart
  .order-name
    = " PRODUCT: 　#{@order.product.name}"
  .order-price
    = " PRICE: 　¥#{@order.product.price.to_s(:delimited)}"
  .order-count
    = " COUNT: 　#{@order.count}"
  .order-size
    = " SIZE: 　#{@order.size}"
  .order-color
    = " COLOR: 　#{@order.color}"
  .order-total-price
    = "TOTAL-PRICE: 　¥#{(@order.product.price * @order.count).to_s(:delimited)}"
  = link_to '→PRODUCTS LIST', products_path, class: 'products-page-back'
  = link_to '→GO CART', cart_products_path, class: 'cart-page-go'

app/views/products/history.html.haml
= render partial: 'layouts/header-black'

.history
  .history-space
    - @total_price = 0
    - @orders.each do |order|
      .history-count
        = " PRODUCT: #{order.product.name} ,　"
        = " PRICE: ¥#{order.product.price.to_s(:delimited)} ,　"
        = " COUNT: #{order.count} ,　"
        = " SIZE: #{order.size} ,　"
        = " COLOR: #{order.color}"
        = " =　TOTAL-PRICE: ¥#{(order.product.price * order.count).to_s(:delimited)} "
        - @total_price += (order.product.price * order.count)
  .history-total-space
    .history-price
      = " PRICE: 　¥#{@total_price.to_s(:delimited)} "
    .history-plus-space
      = "+"
    .history-tax-price
      = " TAX: 　¥#{(@total_price * 0.1).floor.to_s(:delimited)}"
    .history-equal-space
      = "="
    .history-total-price
      = " TOTAL-PRICE: 　¥#{(@total_price + (@total_price * 0.1)).floor.to_s(:delimited)} "

app/views/products/index.html.haml
= render partial: 'layouts/header-white'

.products
  .products-search-space
    - @products.each do |product|
      = link_to product_path(product), class: 'product-search' do
        .product-name-search
          = product.name
  .products-space
    - @products.each do |product|
      = link_to product_path(product), class: 'product' do
        = image_tag("/#{product.images[0].image}", class: 'product-image')
        .product-name
          = product.name
        .product-price
          = " ¥ #{product.price.to_s(:delimited)}"

app/views/products/show.html.haml
= render partial: 'layouts/header-black'

.product-detail
  .cover-1
  .cover-2
  .product-detail__image-space
    .product-detail__image-first-space
      .product-detail__image-first
        = image_tag("/#{@product.images[0].image}", class: 'product-image-1 show')
        - @images[1..3].each do |image|
          = image_tag("/#{image.image}", class: 'product-image-1')
    .product-detail__image-other
      = image_tag("/#{@product.images[0].image}", class: 'product-image-2 active')
      - @images[1..3].each do |image|
        = image_tag("/#{image.image}", class: 'product-image-2')
  .product-detail__select
    .product-detail__select-name
      = @product.name
    .product-detail__select-description
      = @product.description
    .product-detail__select-price
      = " ¥ #{@product.price.to_s(:delimited)} (+tax)"
    = form_with model: @order,url: create_order_products_path, local: true do |f|
      .count
        %p.count-name COUNT
        = f.select :count, [["--", 0],["1", 1],["2", 2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9]], {}, class: 'count-space'
      .size
        %p.size-name SIZE
        = f.select :size, Order.sizes.keys.map {|k| [I18n.t("enums.order.size.#{k}"), k]}, {}, class: 'size-space'
      .color
        %p.color-name COLOR
        = f.select :color, Order.colors.keys.map {|k| [I18n.t("enums.order.color.#{k}"), k]}, {}, class: 'color-space'
      = f.hidden_field :product_id, value: @product.id
      .cart-btn-space
        = f.submit 'Add to cart', class: 'cart-btn'


= javascript_include_tag 'product-show.js'