config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}

  # devise_scope :user do #ログイン関係のパス名をloginとlogoutに変更
  #   get "sign_up", to: "users/registrations#new"
  #   post "", to: "users/registrations#create"
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'views#index'

  resources :views, only: [:index] do
    collection do
      get 'news'
      get 'about'
    end
  end

  resources :products, only: [:index, :show, :destroy] do
    collection do
      get 'cart'
      patch 'purchase'
      post 'pay'
      get 'history'
      post 'create', to: "products#create", as: :create_order
    end
    resources :pays, only: [:index] do
      collection do
        post 'pay'
        get 'done'
      end
    end
  end
  resources :users, only: [:index] do
    collection do
      get 'address'
      post 'address_create'
      get 'card'
      post 'card_create'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  VALID_POSTAL_CODE = /\A\d{3}-?\d{4}\z/

  validates :zip, presence: true, length: { maximum: 8 }, format: { with: VALID_POSTAL_CODE, message: 'は有効でありません。' }
  validates :prefecture, presence: true
  validates :city_name, presence: true, length: { maximum: 50 }
  validates :block_name, presence: true, length: { maximum: 100 }
  validates :bill_name, length: { maximum: 100 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :order_statuses

  validates :count, presence: true
  validates :size, presence: true
  validates :color, presence: true


  enum size:{
    '--':      0, #--
    S:         1, #S
    M:         2, #M
    L:         3, #L
    LL:        4, #LL
  },_prefix: true

  enum color:{
    '--':           0, #--
    white:          1, #white
    black:          2, #black
    orange:         3, #orange
  },_prefix: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  belongs_to :order
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'},{id: 48, name: '未定'}, 
  ]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :sizes
  has_many :colors
  has_many :orders
  belongs_to :category
  belongs_to :status
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :product
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,255}\z/i
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  VALID_POSTAL_CODE = /\A\d{3}-?\d{4}\z/

  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'は有効でありません。' }
  validates :password, presence: true, length: { in: 7..255 }, format: { with: VALID_PASSWORD_REGEX, message: 'は255文字以下に設定して下さい'}
  validates :birthday, presence: true
  validates :last_name, presence: true, length: { maximum: 20 }, on: :validates_step1
  validates :first_name, presence: true, length: { maximum: 20 }, on: :validates_step1
  validates :last_name_kana, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい。'}
end

app/controllers/pays_controller.rb
class PaysController < ApplicationController
  def index
  end
  
  def pay
    card = Card.where(user_id: current_user.id).first
    @orders = Order.where(user_id: current_user.id, order_status_id: 1)
    @total_price = (@orders.product.price.sum * 1.1)
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    charge = Payjp::Charge.create(
    amount: @total_price,
    customer: card.customer_id,
    currency: :'jpy',
    )
    @orders.update(order_status_id: 2)
    if @orders.save(validate: false)
      redirect_to cart_products_path
    else
      flash[:notice] = '問題が発生して処理を中止しました。'
      redirect_to root_path
    end
  end

  def done
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end

  def address
    @address = Address.new
  end

  def address_create
    @address = Address.new(address_params)
    if @address.save
      redirect_to cart_products_path
    else
      redirect_to address_users_path
    end
  end

  def card
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def card_create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "show"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to controller: "signup", action: "user_registration4"
      else
        redirect_to action: "pay"
      end
    end
  end

  private

  def address_params
    params.require(:address).permit(:zip, :prefecture, :city_name, :block_name, :bill_name).merge(user_id: current_user.id)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :authenticate_user!, only: [:mypage]
  def index
  end

  def about
  end

  def news
  end

  def mypage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/layouts/_header-black.html.haml
.header-black
  = link_to 'SECURUS', root_path, class: "header-black__title"
  %p.header-black__sub-title - MAKE THE STREET -
  .header-black__btn
    - if user_signed_in?
      = link_to 'NEWS', news_views_path, class: "header-black__btn-news"
      = link_to 'PRODUCTS', products_path, class: "header-black__btn-products"
      = link_to 'ABOUT', about_views_path, class: "header-black__btn-about"
      = link_to 'MYPAGE', users_path, class: "header-black__btn-mypage"
      = link_to 'CART', cart_products_path, class: "header-black__btn-cart"
    - else
      = link_to 'NEWS', news_views_path, class: "header-black__btn-news"
      = link_to 'PRODUCTS', products_path, class: "header-black__btn-products"
      = link_to 'ABOUT', about_views_path, class: "header-black__btn-about"
      = link_to 'SIGN-UP', new_user_registration_path, class: "header-black__btn-signup"
      = link_to 'LOG-IN', new_user_session_path, class: "header-black__btn-login"

= javascript_include_tag 'header-black.js'

app/views/layouts/_header-white.html.haml
.header-white
  = link_to 'SECURUS', root_path, class: "header-white__title"
  %p.header-white__sub-title - MAKE THE STREET -
  .header-white__btn
    - if user_signed_in?
      = link_to 'NEWS', news_views_path, class: "header-white__btn-news"
      = link_to 'PRODUCTS', products_path, class: "header-white__btn-products"
      = link_to 'ABOUT', about_views_path, class: "header-white__btn-about"
      = link_to 'MYPAGE', users_path, class: "header-white__btn-mypage"
      = link_to 'CART', cart_products_path, class: "header-white__btn-cart"
    - else
      = link_to 'NEWS', news_views_path, class: "header-white__btn-news"
      = link_to 'PRODUCTS', products_path, class: "header-white__btn-products"
      = link_to 'ABOUT', about_views_path, class: "header-white__btn-about"
      = link_to 'SIGN-UP', new_user_registration_path, class: "header-white__btn-signup"
      = link_to 'LOG-IN', new_user_session_path, class: "header-white__btn-login"

= javascript_include_tag 'header-white.js'

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{content: "text/html: charset=UTF-8", "http-equiv": "Content-Type"}/
    %title SECURUS
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body

    = yield

app/views/views/about.html.haml
= render partial: 'layouts/header-black'

.left-images
.about
  %p.about-title ABOUT
  %p.about-description
    SECURUS　＝　自由気ままに<br>
    をテーマに作られたアパレルブランド。<br><br>
    設立は2015年の冬。<br><br>
    masaki（Designer)を中心に<br>
    ストリート系のプロダクトを<br>
    生み出し続けている。<br><br>
    サブテーマには<br>
    make the street<br>
    という言葉があり、<br>
    自ら道を切り開くという<br>
    信念が込められている。<br>
.right-images

= javascript_include_tag 'about.js'

app/views/views/form.html.haml
= render partial: 'layouts/header-black'

.form

app/views/views/index.html.haml
.header
  %p.header__title SECURUS
  %p.header__sub-title - MAKE THE STREET -
  .header__btn
    - if user_signed_in?
      = link_to 'NEWS', news_views_path, class: "header__btn-news"
      = link_to 'PRODUCTS', products_path, class: "header__btn-products"
      = link_to 'ABOUT', about_views_path, class: "header__btn-about"
      = link_to 'MYPAGE', users_path, class: "header__btn-mypage"
      = link_to 'CART', cart_products_path, class: "header__btn-cart"
    - else
      = link_to 'NEWS', news_views_path, class: "header__btn-news"
      = link_to 'PRODUCTS', products_path, class: "header__btn-products"
      = link_to 'ABOUT', about_views_path, class: "header__btn-about"
      = link_to 'SIGN-UP', new_user_registration_path, class: "header__btn-signup"
      = link_to 'LOG-IN', new_user_session_path, class: "header__btn-login"
.main
  = image_tag("/top-1.jpeg", class: "main-1")
  = image_tag("/top-2.jpeg", class: "main-2")
  = image_tag("/top-3.jpeg", class: "main-3")
  = image_tag("/top-4.jpeg", class: "main-4")
.gray

= javascript_include_tag 'views.js'

app/views/views/news.html.haml
= render partial: 'layouts/header-black'

.news
  = link_to '/products/11', class: "news-1" do
    .news-1-cover
    %p.news-1-title Hand Eye Trainer/black ¥12,000
    = image_tag("/news-1-1.jpeg", class: 'news-1-1-image')
    = image_tag("/news-1-2.jpeg", class: 'news-1-2-image')
    = image_tag("/news-1-3.jpeg", class: 'news-1-3-image')
    = image_tag("/news-1-4.jpeg", class: 'news-1-4-image')
  = link_to '/products/5', class: "news-2" do
    .news-2-cover
    %p.news-2-title Sticker T-shirts/orange ¥6,000
    = image_tag("/news-2-1.jpeg", class: 'news-2-1-image')
    = image_tag("/news-2-2.jpeg", class: 'news-2-2-image')
    = image_tag("/news-2-3.jpeg", class: 'news-2-3-image')
    = image_tag("/news-2-4.jpeg", class: 'news-2-4-image')
  = link_to '/products/2', class: "news-3" do
    .news-3-cover
    %p.news-3-title Triangle T-shirts/white ¥6,000
    = image_tag("/news-3-1.jpeg", class: 'news-3-1-image')
    = image_tag("/news-3-2.jpeg", class: 'news-3-2-image')
    = image_tag("/news-3-3.jpeg", class: 'news-3-3-image')
    = image_tag("/news-3-4.jpeg", class: 'news-3-4-image')
  = link_to 'javascript:void(0)', class: "news-4" do
    .news-4-cover
    %p.news-4-title Coming Soon...
    = image_tag("/news-4-1.jpeg", class: 'news-4-1-image')
    = image_tag("/news-4-4.jpeg", class: 'news-4-4-image')

= javascript_include_tag 'news.js'